//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int cid { get; set; }
        public string cname { get; set; }
        public Nullable<long> mobile { get; set; }
        public string nationality { get; set; }
        public string gender { get; set; }
        public string dob { get; set; }
        public string idproof { get; set; }
        public string checkin { get; set; }
        public string checkout { get; set; }
        public string chekout { get; set; }
        public int roomid { get; set; }
    }
}
