//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int eid { get; set; }
        public string ename { get; set; }
        public long mobile { get; set; }
        public string gender { get; set; }
        public string emailid { get; set; }
        public string username { get; set; }
        public string pass { get; set; }
        public string type { get; set; }
    }
}
