//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class room
    {
        public string TENTANG { get; set; }
        public int roomid { get; set; }
        public string roomNo { get; set; }
        public string roomType { get; set; }
        public int bed { get; set; }
        public long price { get; set; }
        public string booked { get; set; }
        public Nullable<int> SONGUOI { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
    }
}
